name: .NET Core

on:
  push:
    branches: [ master ]
    paths: 
      - 'src/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'src/**'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore .\src\Carp.csproj
    - name: Build
      run: dotnet build .\src\Carp.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test .\src\Carp.csproj --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet publish .\src\Carp.csproj -c Release -o carpdoc 
    - name: 'Azure Deploy'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: carpdoc # Replace with your app name
        publish-profile: ${{ secrets.publish_profile }} # Define secret variable in repository settings as per action documentation
        package: './carpdoc'